# Рабочая тетрадь №2
**Цель** машинного обучения – **анализ данных**.

Данные – зарегистрированная информация; представление фактов,
понятий или инструкций в форме, приемлемой для общения,
интерпретации, или обработки человеком или с помощью автоматических
средств (ISO/IEC/IEEE 24765-2010).
Данные в машинном обучении – **это представление информации об
исследуемой задаче в виде множеств исследуемых объектов и множеств их характеристик**, на основе которых строятся модели, разрабатываются подходы, методы и алгоритмы анализа для принятия решений.
**Качество данных** – важный аспект машинного обучения.
Для Аналитика (Data Scientist, Data Analyst, Data Mining Engineer)
очень важно обладать правильными данными, что гарантирует
эффективность обработки и построении прогнозов. Ниже
представлены основные требования к данным

- доступность
- точность
- полнота
- непротиворечивость
- однозначность
- релевантность
- надежность
- своевременность
- взаимосвязанность


Остановимся на основных этапах решения задач машинного
обучения.
Этапы решения задач машинного обучения:
1. Постановка задачи.
2. Сбор и подготовка данных.
3. Предобработка данных и выделение ключевых признаков.
4. Выбор алгоритмов машинного обучения.
5. Обучение модели (моделей).
6. Оценка качества.
7. Эксплуатация модели.
При подготовке данных можно применять следующие операции:
- структурирование – приведение данных к табличному (матричному)
виду;
- заполнение пропусков;
- отбор – исключение записей с отсутствующими или некорректными
значениями, если нет возможности заполнения и устранения
противоречивости;
- нормализация – приведение числовых значений к определенному
диапазону, например к диапазону 0...1;
- кодирование – это представление категориальных данных в числовой
форме.

NumPy (NumericalPython) - это библиотека Python с открытым
исходным кодом, которая используется практически во всех областях науки
и техники. Это универсальный стандарт для работы с числовыми данными в Python.
Если у вас уже есть Python, вы можете установить NumPy с помощью
командной строки:
> pip install numpy

Чтобы начать использовать NumPy необходимо импортировать
соответствующую библиотеку:
 import numpy as np
Основным объектом NumPy является однородный многомерный
массив (в numpy называется numpy.ndarray). Это многомерный массив
элементов (обычно чисел), одного типа.
Наиболее важные атрибуты объектов ndarray:
ndarray.ndim - число измерений (чаще их называют "оси") массива.
ndarray.shape - размеры массива, его форма. Это кортеж натуральных
чисел, показывающий длину массива по каждой оси. Для матрицы из n строк
и m столбов, shape будет (n,m). Число элементов кортежа shape равно ndim.
ndarray.size - количество элементов массива. Очевидно, равно
произведению всех элементов атрибута shape.
ndarray.dtype - объект, описывающий тип элементов массива. Можно
определить dtype, используя стандартные типы данных Python. NumPy здесь
предоставляет целый букет возможностей, как встроенных, например: bool_,
character, int8, int16, int32, int64, float8, float16, float32, float64, complex64,
object_, так и возможность определить собственные типы данных, в том
числе и составные.
ndarray.itemsize - размер каждого элемента массива в байтах.
ndarray.data - буфер, содержащий фактические элементы массива.
Обычно не нужно использовать этот атрибут, так как обращаться к
элементам массива проще всего с помощью индексов.
Подробнее о массивах в NumPy можно найти в официальной
документации https://numpy.org/doc/stable/user/absolute_beginners.html

## 1.2.1
### Пример
> Задача: Создать массив 5x2. Создать массив 5x2. Вывести все значения массива, значение элемента с индексом (3,1) и второй столбец. Индексация начинается с нуля. Решение:

In [2]:
import numpy as np
x = np.array([[1,2], [3, 4], [5,6], [7,8], [9,10]])
print(x)
print(x[3][1])
print(x[1])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
8
[3 4]


## 1.2.2 
### Пример
 >  Выполнить следующее:
  1.Создать вектор (одномерный массив) размера 10, заполненный нулями. 
  2.Создать вектор размера 10, заполненный единицами.
  3.Создать вектор размера 10, заполненный заданным числом.
  4.Создать вектор со значениями от 10 до 19.

In [3]:
import numpy as np
a = np.zeros(10)
b = np.ones(10)
c = np.full(10, 5)
d = np.arange(10, 20)
print(a, "\n", b, "\n", c, "\n", d)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 
 [5 5 5 5 5 5 5 5 5 5] 
 [10 11 12 13 14 15 16 17 18 19]


## 1.2.3
### Пример
> Создать массив 10x10 со случайными значениями, найти минимум, максимум и среднее значение.

In [4]:
import numpy as np
Z = np.random.random((10, 10))
Zmin, Zmax, Zmean = Z.min(), Z.max(), Z.mean()
print(Zmin, Zmax, Zmean)

0.007052053597290553 0.9995316129107218 0.5200777273234815


## 1.2.4
### Пример 
> Задать матрицу размерности 5 на 5 и поменять 2 строки в матрице местами.

In [5]:
import numpy as np
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


## 1.2.5
### Пример
> Выяснить результат следующих выражений:

> 0 * np.nan

> np.nan == np.nan

> np.inf > np.nan

> np.nan - np.nan

> 0.3 == 3 * 0.1

In [6]:
import numpy as np
print(0 * np.nan) # любая операция с nan дает nan
print(np.nan == np.nan) # nan не равен никакому другому значению, даже самому себе
print(np.inf > np.nan) #несравнимы
print(np.nan - np.nan) 
print(0.3 == 3 * 0.1) #IEEE 


nan
False
False
nan
False


## 1.2.6
## Пример
> Отсортировать массив

In [9]:
arr = np.array([2,1,5,3,7,4,6])
print(np.sort(arr))

[1 2 3 4 5 6 7]


## 1.3.1
> Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.


In [15]:
import numpy as np
arr = np.zeros(64).reshape(8, 8) # возвращает число строк в массиве
for i in range(arr.shape[0]):
    for j in range(arr.shape[0]):
        if (i + j) % 2 == 0:
            arr[i, j] = 1
print(arr)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


## 1.3.2
> Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания необходимо использовать функцию arange.


In [25]:
import numpy as np

arr = np.arange(25).reshape(5, 5)

for i in range(5):
    arr[i, :] = i

print(arr)

[[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]]


## 1.3.3
> Создать массив 3х3х3 со случайными значениями

In [17]:
import numpy as np
arr = np.random.random((3, 3, 3))
arr.reshape(3,3,3)
print(arr)

[[[0.94693366 0.67321346 0.62572735]
  [0.34789824 0.19443547 0.45729337]
  [0.43261401 0.57312317 0.58921119]]

 [[0.98968557 0.06413089 0.71684569]
  [0.80546338 0.5315006  0.74257991]
  [0.18836107 0.60421344 0.99602013]]

 [[0.07162674 0.52028986 0.99907507]
  [0.52982083 0.84338325 0.39354371]
  [0.04786321 0.76657869 0.50206907]]]


## 1.3.4
> Создать матрицу с 0 внутри и 1 на границах

In [18]:
import numpy as np

arr = np.zeros((5, 5))

arr[0,:] = 1
arr[-1,:] = 1
arr[:,0] = 1
arr[:,-1] = 1

print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## 1.3.5
> Создайте матрицу, выведите ее форму, размер и размерность

In [26]:
import numpy as np

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Форма матрицы:", matrix.shape)

print("Размер матрицы:", matrix.size)

print("Размерность матрицы:", matrix.ndim)


Форма матрицы: (3, 3)
Размер матрицы: 9
Размерность матрицы: 2


## 2.1. Теоретический материал – Библиотека Pandas
Первым шагом в любом начинании в области машинного обучения
является введение исходных данных в систему. Исходные данные могут
вводиться вручную, содержаться в файле или храниться в интернете в какомлибо формате. Кроме того, часто требуется получить данные из нескольких
источников.
Библиотека pandas – это удобный и быстрый инструмент для работы
с данными, обладающий большим функционалом. Если очень кратко, то
pandas – это библиотека, которая предоставляет очень удобные с точки
зрения использования инструменты для хранения данных и работе с ними.
Библиотека pandas присутствует в стандартной поставке Anaconda.
Если же ее там нет, то его можно установить отдельно. Для этого введите
командной строке:
> pip install pandas

Для импорта библиотеки используйте команду:
import pandas as pd
Библиотека pandas предоставляет две ключевые структуры данных:
Series и DataFrame.
Series – это одномерная структура данных, ее можно представить, как
таблицу с одной строкой. С Series можно работать как с обычным массивом
(обращаться по номеру индекса), и как с ассоциированным массивом, когда
можно использовать ключ для доступа к элементам данных.
DataFrame – это двумерная структура. Идейно она очень похожа на
обычную таблицу, что выражается в способе ее создания и работе с ее
элементами

## 2.2.1
### Пример

>Создать Series из списка Python, словаря Python, и массива Numpy
(установить буквенные метки для последнего)

In [27]:
import pandas as pd
lst = [1, 2, 3, 4, 5]
d = {'a': 1, 'b': 2, 'c':3}
ndarr = np.array([1,2,3,4,5])

s1 = pd.Series(lst)
s2 = pd.Series(d)
s3 = pd.Series(ndarr, ['a', 'b', 'c', 'd', 'e'])

print(s1)
print(s2)
print(s3)

0    1
1    2
2    3
3    4
4    5
dtype: int64
a    1
b    2
c    3
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int32


## 2.2.2
### Пример
> Дано два Series. Напечатать их первые элементы и все элементы после
третьего (во втором фрейме).

In [33]:
import pandas as pd
s1 = pd.Series([1, 2, 3, 4, 5], ['a', 'b', 'c', 'd', 'e'])
s2 = pd.Series([5, 4, 3, 2, 1])
print(s1['a'])
print(s2[0])
print(s2[3:])

1
5
3    2
4    1
dtype: int64


## 2.2.3
### Пример
> Создайте новый фрейм данных

In [3]:
import pandas as pd
dataframe = pd.DataFrame()
dataframe['Имя'] = ['Джеки Джексон','Стивен Стивенсон']
dataframe['Возраст'] = [28, 35]
dataframe['Водитель'] = [True, False]
dataframe

Имя  Возраст  Водитель
0     Джеки Джексон       28      True
1  Стивен Стивенсон       35     False

## 2.2.4
### Пример
> Загрузите фрейм данных по ссылке:
https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titan
ic.csv

In [4]:
url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'
dataframe = pd.read_csv(url)
dataframe.head(5)

Name PClass    Age     Sex   
0                   Allen, Miss Elisabeth Walton    1st  29.00  female  \
1                    Allison, Miss Helen Loraine    1st   2.00  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.00    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
4                  Allison, Master Hudson Trevor    1st   0.92    male   

   Survived  SexCode  
0         1        1  
1         0        1  
2         0        0  
3         0        1  
4         1        0

## 2.2.5
### Пример
> Пронализировать характеристики фрейма данных

Одна из самых простых вещей, которые мы можем сделать после
загрузки данных, – это взглянуть на первые несколько строк с помощью
метода head. На последние строки можно посмотреть с помощью
функции tail. Мы также можем взглянуть на количество строк и
столбцов: dataframe.shape. Кроме того, используя метод describe, мы
можем получить описательную статистику для любых числовых
столбцов.

In [7]:
# import pandas as pd
# url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'
# dataframe = pd.read_csv(url)
dataframe.head(2)
dataframe.tail(3)
dataframe.shape
dataframe.describe()

Age     Survived      SexCode
count  756.000000  1313.000000  1313.000000
mean    30.397989     0.342727     0.351866
std     14.259049     0.474802     0.477734
min      0.170000     0.000000     0.000000
25%     21.000000     0.000000     0.000000
50%     28.000000     0.000000     0.000000
75%     39.000000     1.000000     1.000000
max     71.000000     1.000000     1.000000

Более подробно с возможностями работы с фреймами данных
можно узнать по ссылке ниже:
> https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html

## 2.2.6
### Пример
> Выберите индивидуальные данные или срезы фрейма данных.


Для выбора одной или нескольких строк, либо значений, можно
использовать методы 1ос или iloc.

In [9]:
dataframe.iloc[1:4]

Name PClass   Age     Sex   
1                    Allison, Miss Helen Loraine    1st   2.0  female  \
2            Allison, Mr Hudson Joshua Creighton    1st  30.0    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.0  female   

   Survived  SexCode  
1         0        1  
2         0        0  
3         0        1

## 2.2.7
### Пример
> Требуется отобрать строки фрейма данных на основе некоторого
условия. Необходимо сформировать новый фрейм данных из пассажиров
первого класса.

In [15]:
dataframe[dataframe['PClass'] == "1st"].head(2)

Name PClass   Age     Sex  Survived  SexCode
0  Allen, Miss Elisabeth Walton    1st  29.0  female         1        1
1   Allison, Miss Helen Loraine    1st   2.0  female         0        1

## 2.3.1
> Найдите евклидово расстояние между двумя Series (точками) a и b, не
используя встроенную формулу

> Евклидова метрика (евклидово расстояние) — метрика в евклидовом пространстве — расстояние между двумя точками евклидова пространства, вычисляемое по теореме Пифагора.

In [16]:
import numpy as np
import pandas as pd

a = pd.Series([1, 2, 3])
b = pd.Series([4, 5, 6])

diff = a - b # результатом является новый объект Series, содержащий разности элементов.
diff_squared = diff ** 2 # возводим результат вычитания в квадрат,
# чтобы убедиться, что разность всегда будет положительной.
#  eсли мы просто взяли бы абсолютное значение разности, 
# это бы не сработало, потому что две точки могут находиться
#  как в одном направлении, так и в противоположных направлениях 
# относительно начала координат.
sum_diff_squared = diff_squared.sum()
dist = np.sqrt(sum_diff_squared)

print(dist)


5.196152422706632


## 2.3.2
> Найдите в Интернете ссылку на любой csv файл и сформируйте из него
фрейм данных (например, коллекцию фреймов данных можно найти
здесь: https://github.com/akmand/datasets).

In [17]:
import pandas as pd

url = "https://raw.githubusercontent.com/akmand/datasets/main/airlines.csv"

dataframe = pd.read_csv(url)

dataframe.head(10)

Airline  Flight AirportFrom AirportTo  DayOfWeek  Time  Length  Delay
0      CO     269         SFO       IAH          3    15     205      1
1      US    1558         PHX       CLT          3    15     222      1
2      AA    2400         LAX       DFW          3    20     165      1
3      AA    2466         SFO       DFW          3    20     195      1
4      AS     108         ANC       SEA          3    30     202      0
5      CO    1094         LAX       IAH          3    30     181      1
6      DL    1768         LAX       MSP          3    30     220      0
7      DL    2722         PHX       DTW          3    30     228      0
8      DL    2606         SFO       MSP          3    35     216      1
9      AA    2538         LAS       ORD          3    40     200      1

## 2.3.3
> Проделайте с получившемся из предыдущего задания фреймом данных
те же действия, что и в примерах 2.2.5-2.2.7

In [29]:
import pandas as pd

url = "https://raw.githubusercontent.com/pandas-dev/pandas/master/doc/data/tips.csv"

dataframe = pd.read_csv(url)

dataframe.head(5)
dataframe.tail(5)
dataframe.iloc[1:6]
dataframe.shape
dataframe.describe()

# dataframe[dataframe['AirportFrom'] == "LAX"].head(5)


total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

# 3.1 Теоретический материал – Работа с числовыми данными
> Количественные данные что-то измеряют – будь то размер класса,
ежемесячные продажи или оценки учащихся. Естественным способом
представления этих величин является численным (например, 150 студентов,
$529 392 продаж).
Нормализация данных — это общепринятая задача предобработки в
машинном обучении. Многие алгоритмы предполагают, что все признаки
находятся в единой шкале, как правило, от 0 до 1 или от -1 до 1.
Существует множество способов нормализации значений признаков,
чтобы масштабировать их к единому диапазону и использовать в различных
моделях машинного обучения. В зависимости от используемой функции, их
можно разделить на 2 большие группы: линейные и нелинейные. При
нелинейной нормализации в расчетных соотношениях используются
функции логистической сигмоиды или гиперболического тангенса. В
линейной нормализации изменение переменных осуществляется
пропорционально, по линейному закону.
На практике наиболее распространены следующие методы
нормализации признаков:
 Минимакс – линейное преобразование данных в диапазоне [0..1], где
минимальное и максимальное масштабируемые значения
соответствуют 0 и 1 соответственно;
 Z-масштабирование данных на основе среднего значения и
стандартного отклонения: производят деление разницы между
переменной и средним значением на стандартное отклонение.
При масштабировании данных мы будем использовать одну из
популярных библиотек машинного обучения Scikit-learn. Библиотека
содержит пакет sklearn.preprocessing, который предоставляет широкие
возможности для нормализации данных. Следует отметить, что в целом
алгоритмы обучения выигрывают от стандартизации набора данных.

## 3.2.1 
### Пример
> Прошкалируйте числовой признак в диапазон между двумя значениями.

In [ ]:
from sklearn import preprocessing
import numpy as np
feature = np.array([[-500.5], [-100.1], [0], [100.1], [900.9]])
minmax_scale = preprocessing.MinMaxScaler(feature_range=(0, 1))
scaled_feature = minmax_scale.fit_transform(feature)
print(scaled_feature)