## 1.2.1
### Пример
> Задача: Создать массив 5x2. Создать массив 5x2. Вывести все значения массива, значение элемента с индексом (3,1) и второй столбец. Индексация начинается с нуля. Решение:

In [2]:
import numpy as np
x = np.array([[1,2], [3, 4], [5,6], [7,8], [9,10]])
print(x)
print(x[3][1])
print(x[1])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
8
[3 4]


## 1.2.2 
### Пример
 >  Выполнить следующее:
  1.Создать вектор (одномерный массив) размера 10, заполненный нулями. 
  2.Создать вектор размера 10, заполненный единицами.
  3.Создать вектор размера 10, заполненный заданным числом.
  4.Создать вектор со значениями от 10 до 19.

In [3]:
a = np.zeros(10)
b = np.ones(10)
c = np.full(10, 5)
d = np.arange(10, 20)
print(a, "\n", b, "\n", c, "\n", d)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 
 [5 5 5 5 5 5 5 5 5 5] 
 [10 11 12 13 14 15 16 17 18 19]


## 1.2.3
### Пример
> Создать массив 10x10 со случайными значениями, найти минимум, максимум и среднее значение.

In [4]:
Z = np.random.random((10, 10))
Zmin, Zmax, Zmean = Z.min(), Z.max(), Z.mean()
print(Zmin, Zmax, Zmean)

0.008916223472822948 0.9986974928117845 0.49928714880788966
